services:
  - type: web
    name: labsync-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: NODE_ENV
        value: production
      - key: SPREADSHEET_ID
        value: 1swE1x8y7xNFaPFZovR9BJ6usq7baM3gGkXqNI8cgWmI
      - key: JWT_SECRET
        value: labsync_jwt_secret_key_2026
