services:
  - type: web
    name: labsync-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: NODE_ENV
        value: production
      - key: SPREADSHEET_ID
        value: 1swF1x8y7xNFAF7Ovr9R86usq7baM3gGkXqNl8rgWmI
      - key: JWT_SECRET
        value: labsync_jwt_secret_key_2026
